# Generated by Django 4.1.7 on 2023-03-19 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_cover_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
