# Generated by Django 4.1.7 on 2023-07-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('articles', '0003_alter_article_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='long_cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles_photos'),
        ),
        migrations.AddField(
            model_name='article',
            name='long_cover_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='long_cover_author', to='authors.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='long_cover_theme',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('dark', 'dark')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='main_article',
            field=models.BooleanField(default=False),
        ),
    ]
