# Generated by Django 4.1.7 on 2023-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_long_cover_article_long_cover_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='long_cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles_long_covers'),
        ),
    ]
